version: '3.8'

services:
  web:
    build: .
    command: bash -c 'uvicorn app.main.main:app --host 0.0.0.0 --port 8001 --reload'
    volumes:
      - .:/app
    ports:
      - 8001:8001
    env_file:
      - .env