version: '3.8'

services:
  database:
    image: postgres:15-alpine
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DevTeamTask