version: '3.8'

services:
  web:
    build: .
    command: bash -c 'uvicorn app.infra.main:app --host 0.0.0.0 --port 8002 --reload'
    volumes:
      - .:/app
    ports:
      - 8002:8002
    env_file:
      - .env